### ISSUE TITLE
Invalid `GIT_REMOTE_URL`?

### ISSUE THREAD

**Issue by Benjamint22** [dokku/gitlab-ci#4]
Using the following config file, based on `simple.yml`, gave me an error that stopped the deployment:
<details>
<summary>.gitlab-ci.yml</summary>

```yaml
image: dokku/ci-docker-image

stages:
  - deploy

variables:
  GIT_DEPTH: 0

deploy:
  stage: deploy
  only:
    - master
  variables:
    GIT_REMOTE_URL: ssh://dokku@benjamintaillon.com:22/discorddroid
  environment:
    name: production
  script: 
    - dokku-deploy
  after_script: 
    - dokku-unlock

```
</details>

![image](https://user-images.githubusercontent.com/6548393/131262641-2660339f-3fb3-4f7a-9f38-5a08e388c05d.png)

After updating it to the following, it worked:
<details>
<summary>.gitlab-ci.yml (diff)</summary>

```diff
image: dokku/ci-docker-image

stages:
  - deploy

variables:
  GIT_DEPTH: 0

deploy:
  stage: deploy
  only:
    - master
  variables:
-   GIT_REMOTE_URL: ssh://dokku@benjamintaillon.com:22/discorddroid
+   GIT_REMOTE_URL: ssh://dokku@benjamintaillon.com:22/~/discorddroid
  environment:
    name: production
  script: 
    - dokku-deploy
  after_script: 
    - dokku-unlock

```
</details>

Could it have something to do with my local setup? I'm opening this issue just in case the issue may be more widespread.
