### ISSUE TITLE
Can't rollback environment

### ISSUE THREAD

**Issue by macier-pro** [dokku/gitlab-ci#8]
### Steps to Reproduce

1. Deploy to environment (commit 1)
2. Deploy to environment (commit 2)
3. Rollback deployment (commit 1)

![image](https://github.com/user-attachments/assets/40f2d9ad-c062-4323-b6a3-84af73d07858)

#### Actual Results

```
To ssh://deploy.runner.iiens.net/connect
 ! [rejected]        b896adc9aebc993bbee196e069f3e65f69a8e408 -> main (non-fast-forward)
error: failed to push some refs to 'ssh://deploy.runner.iiens.net/connect'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. If you want to integrate the remote changes, use 'git pull'
hint: before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

#### Expected Results

The environment should be redeployed from the older commit, using `--force` as the pushed commit is behind its remote

### `.gitlab-ci.yaml`

```yaml
stages:
  - deploy

deploy:
  stage: deploy
  only:
    - main
  when: manual
  image: dokku/ci-docker-image
  services: []
  variables:
    GIT_DEPTH: 0
    BRANCH: main
    GIT_REMOTE_URL: ssh://dokku@deploy.runner.iiens.net/connect
  script: dokku-deploy
  before_script: []
  after_script: [dokku-unlock]
  environment:
    name: production
    url: https://connect.iiens.net/
```
